# Generated by Django 6.0.4 on 2026-04-13 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_emoji', models.CharField(default='👤', max_length=5)),
                ('household_size', models.IntegerField(default=2)),
                ('dietary_preferences', models.JSONField(default=list)),
                ('weekly_waste_goal', models.IntegerField(default=0, help_text='Target: 0 items wasted per week')),
                ('total_items_saved', models.IntegerField(default=0)),
                ('total_items_wasted', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_active', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
