# Generated by Django 6.0.4 on 2026-04-13 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('dessert', 'Dessert'), ('any', 'Any Time')], default='any', max_length=20)),
                ('prep_time', models.IntegerField(default=15, help_text='Minutes')),
                ('cook_time', models.IntegerField(default=20, help_text='Minutes')),
                ('servings', models.IntegerField(default=2)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('health_tags', models.JSONField(default=list)),
                ('is_weekend_special', models.BooleanField(default=False)),
                ('calories_per_serving', models.IntegerField(blank=True, null=True)),
                ('image_emoji', models.CharField(default='🍽️', max_length=5)),
                ('instructions', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=100)),
                ('is_optional', models.BooleanField(default=False)),
                ('substitutes', models.JSONField(default=list)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('category', models.CharField(choices=[('optimal', 'Optimal'), ('partial', 'Partial'), ('low', 'Low')], max_length=20)),
                ('context', models.CharField(choices=[('expiry', 'Use Before Expiry'), ('health', 'Health Benefit'), ('time_of_day', 'Time of Day'), ('weekend', 'Weekend Special'), ('general', 'General')], default='general', max_length=20)),
                ('matched_ingredients', models.JSONField(default=list)),
                ('missing_ingredients', models.JSONField(default=list)),
                ('expiry_items_used', models.JSONField(default=list)),
                ('waste_reduction_score', models.FloatField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
